language: python 
node_js:
  - "8"
python:
  - "3.6"
before_script:
  - export COVERALLS_REPO_TOKEN=$COVERAGE_TOKEN
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
script:
  - ./test.sh
after_success:
  - COVERALLS_REPO_TOKEN=$COVERAGE_TOKEN coveralls