version: '2'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile_deploy
    container_name: twebhook_py_deploy
    environment:
      ENV: develop
    volumes:
      - .:/app
      - ~/.aws/credentials:/root/.aws/credentials
    restart: on-failure