FROM lambci/lambda:build-python3.6
ADD . /app
WORKDIR /app
RUN pip install -r requirements.txt
# Install nodejs ( base image has node, but not npm? )
RUN \
curl -sL https://rpm.nodesource.com/setup_9.x | bash && \
yum install -y nodejs && \
yum clean all
RUN npm install
CMD ["./deploy.sh"]