version: '2'
services:
  deploy:
    build:
      context: .
      dockerfile: docker/Dockerfile_deploy
    container_name: twebhook_py_deploy
    environment:
      ENV: develop
    volumes:
      - .:/app
      - ~/.aws/credentials:/root/.aws/credentials
    restart: on-failure

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile_test
    container_name: twebhook_py_test
    environment:
      ENV: develop
    volumes:
      - .:/app
    restart: on-failure
