version: '2'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: twebhook_py
    environment:
      ENV: develop
    volumes:
      - .:/app
    restart: on-failure